In [18]:
# 读取上传的 Excel 文件
import pandas as pd
file_path_excel = R'data\国家认同数据清理后.xlsx'
df_excel = pd.read_excel(file_path_excel)
# 创建民族、年级和政治面貌的交互表
cross_tab = pd.crosstab(index=[df_excel['民族'], df_excel['年级']], 
                        columns=df_excel['政治面貌'], 
                        margins=True)  # All 行和列的总和

cross_tab

政治面貌      1    2   3   4  All
民族  年级
1   0     0    0   1   0    1
    1    93    6   8   2  109
    2    91   15  10   2  118
    3    31   22   6   4   63
    4    22   11   2   0   35
...     ...  ...  ..  ..  ...
36  1     1    0   0   0    1
47  2     1    0   0   0    1
48  1     0    1   0   0    1
97  2     1    0   0   0    1
All     574  103  86  16  779

[78 rows x 5 columns]

In [19]:
from scipy import stats
# 假设我们关注的是第二年级的学生（假设年级用数字“2”表示）
specific_grade = 2

# 筛选出特定年级的数据
df_specific_grade = df_excel[df_excel['年级'] == specific_grade]

# 创建民族和政治面貌的交互表
cross_tab_specific_grade = pd.crosstab(df_specific_grade['民族'], df_specific_grade['政治面貌'])

# 进行卡方检验
chi2_grade, p_grade, dof_grade, expected_grade = stats.chi2_contingency(cross_tab_specific_grade)

chi2_grade, p_grade, dof_grade, expected_grade[:10]  # 展示期望频次的前10个结果，避免过长的输出

(72.71688752254215,
 0.0455610581920747,
 54,
 array([[9.05140562e+01, 1.27951807e+01, 1.23212851e+01, 2.36947791e+00],
        [1.15060241e+01, 1.62650602e+00, 1.56626506e+00, 3.01204819e-01],
        [3.14497992e+01, 4.44578313e+00, 4.28112450e+00, 8.23293173e-01],
        [1.07389558e+01, 1.51807229e+00, 1.46184739e+00, 2.81124498e-01],
        [6.90361446e+00, 9.75903614e-01, 9.39759036e-01, 1.80722892e-01],
        [4.60240964e+00, 6.50602410e-01, 6.26506024e-01, 1.20481928e-01],
        [1.53413655e+00, 2.16867470e-01, 2.08835341e-01, 4.01606426e-02],
        [9.20481928e+00, 1.30120482e+00, 1.25301205e+00, 2.40963855e-01],
        [1.53413655e+00, 2.16867470e-01, 2.08835341e-01, 4.01606426e-02],
        [7.67068273e-01, 1.08433735e-01, 1.04417671e-01, 2.00803213e-02]]))

In [20]:
import pandas as pd
file_path_excel = R'data\国家认同数据清理后.xlsx'

In [21]:
df_excel = pd.read_excel(file_path_excel)
# 创建年级、政治面貌和会打多少分的交互表
cross_tab = pd.crosstab(index=[df_excel['年级'], df_excel['会打多少分']], 
                        columns=df_excel['政治面貌'], 
                        margins=True, normalize=True)  # All 行和列的总和

cross_tab

政治面貌              1         2         3         4       All
年级  会打多少分
0   3      0.005135  0.000000  0.000000  0.000000  0.005135
    4      0.008986  0.000000  0.000000  0.000000  0.008986
    5      0.001284  0.000000  0.001284  0.000000  0.002567
1   1      0.006418  0.000000  0.001284  0.000000  0.007702
    2      0.010270  0.000000  0.001284  0.000000  0.011553
    3      0.032092  0.005135  0.003851  0.003851  0.044929
    4      0.151476  0.007702  0.016688  0.000000  0.175866
    5      0.091142  0.002567  0.010270  0.000000  0.103979
2   1      0.011553  0.001284  0.000000  0.000000  0.012837
    2      0.012837  0.001284  0.001284  0.000000  0.015404
    3      0.043646  0.011553  0.016688  0.001284  0.073171
    4      0.110398  0.007702  0.010270  0.003851  0.132221
    5      0.066752  0.012837  0.005135  0.001284  0.086008
3   1      0.003851  0.002567  0.002567  0.000000  0.008986
    2      0.002567  0.001284  0.000000  0.000000  0.003851
    3      0.025674  0.010270  0.006418  0.001284  0.043646
    4      0.048780  0.033376  0.015404  0.005135  0.102696
    5      0.030809  0.008986  0.003851  0.003851  0.047497
4   1      0.000000  0.002567  0.000000  0.000000  0.002567
    2      0.001284  0.000000  0.001284  0.000000  0.002567
    3      0.010270  0.005135  0.005135  0.000000  0.020539
    4      0.037227  0.007702  0.005135  0.000000  0.050064
    5      0.024390  0.010270  0.002567  0.000000  0.037227
All        0.736842  0.132221  0.110398  0.020539  1.000000

In [22]:
from scipy import stats
# 假设我们关注的是第二年级的学生（假设年级用数字“2”表示）
specific_grade = 1

# 筛选出特定年级的数据
df_specific_grade = df_excel[df_excel['年级'] == specific_grade]

# 创建政治面貌和会打多少分的交互表
cross_tab_specific_grade = pd.crosstab(df_specific_grade['会打多少分'], df_specific_grade['政治面貌'])

# 进行卡方检验
chi2_grade, p_grade, dof_grade, expected_grade = stats.chi2_contingency(cross_tab_specific_grade)

print(chi2_grade,p_grade)
cross_tab_specific_grade

26.390294602838058 0.009448085692166378

政治面貌     1  2   3  4
会打多少分
1        5  0   1  0
2        8  0   1  0
3       25  4   3  3
4      118  6  13  0
5       71  2   8  0

In [23]:
# 创建政治面貌和会打多少分的交互表
cross_tab_specific_grade = pd.crosstab(df_excel['会打多少分'], df_excel['政治面貌'])

# 进行卡方检验
chi2_grade, p_grade, dof_grade, expected_grade = stats.chi2_contingency(cross_tab_specific_grade)
print(chi2_grade, p_grade)

16.22193387826521 0.1812812450681659